version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketing_expenses_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    depends_on:
      - db
    networks:
      - marketing_network

  db:
    image: mysql:8.0
    container_name: marketing_expenses_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: marketing_expenses
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: marketing_user
      MYSQL_PASSWORD: marketing_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - marketing_network

  nginx:
    image: nginx:alpine
    container_name: marketing_expenses_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - marketing_network

volumes:
  mysql_data:
    driver: local

networks:
  marketing_network:
    driver: bridge
